name: Android Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Grant execute permission for gradlew
        run: chmod +x VirtualApp/gradlew

      - name: Build with Gradle
        run: cd VirtualApp && ./gradlew assembleDebug
        env:
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/21.4.7075529

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: virtualapp-debug
          path: 'VirtualApp/**/build/outputs/apk/**/*.apk'
