name: Android Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17 (for sdkmanager)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install NDK
        run: |
          echo "y" | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;16.1.4479499"
          ls -la ${ANDROID_HOME}/ndk/16.1.4479499 || echo "NDK KURULUMU BAŞARISIZ"

      - name: Create local.properties with NDK path
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > VirtualApp/local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/16.1.4479499" >> VirtualApp/local.properties
          cat VirtualApp/local.properties

      - name: Set up JDK 8 (for old Gradle build)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Grant execute permission for gradlew
        run: chmod +x VirtualApp/gradlew

      - name: Build with Gradle
        run: cd VirtualApp && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: virtualapp-debug
          path: 'VirtualApp/**/build/outputs/apk/**/*.apk'
